In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from boruta import boruta_py
import scipy


In [20]:
def gen1(n,p,k):
    data=np.zeros([n,p])
    y=np.zeros(n)
    chik=scipy.stats.chi2.ppf(0.5, k)
    for i in range(p):
        data[:,i]=np.random.normal(0,1,n)
    for i in range(n):
        subset=data[i,0:k]
        sq=subset**2
        if np.sum(sq)<chik:
            y[i]=0
        else:
            y[i]=1
    return data,y
def gen2(n,p,k):
    data=np.zeros([n,p])
    y=np.zeros(n)
    for i in range(p):
        data[:,i]=np.random.normal(0,1,n)
    for i in range(n):
        subset_sum=np.sum(data[i,0:k])
        if subset_sum>k:
            y[i]=1
        else:
            y[i]=0
    return data,y
def combinex_y(x,y):
    train=pd.concat([x,y],axis=1)
    return train


In [21]:
x,y=gen1(20,5,2)
print(x)
print(y)

[[ 0.78080974 -0.00391057 -0.64577659 -0.98194436  1.24849375]
 [-0.10332784 -1.43413561 -0.7105694  -0.08149475  0.44344715]
 [-0.19356816  1.61786161 -0.72488046 -0.26476892  0.59262064]
 [ 1.28557446  3.22183697 -0.35174004 -0.32123946 -0.03645643]
 [ 0.17183039  0.72493805 -1.88734677  1.82742274  0.10383408]
 [-0.81030489 -1.15489234 -0.40096428 -0.65621577  1.00452888]
 [ 1.63400293 -0.1912953  -0.19618505  0.41549235 -0.44135551]
 [ 1.84104972  0.2697368   0.54864819 -0.46688901 -0.51829044]
 [-0.12404769  0.31134865 -1.37318518  0.86938258  0.78830681]
 [ 2.79490697 -0.91164172 -0.46840927 -0.76263711  0.47896758]
 [-0.27181393 -1.13748022 -0.7615454  -0.11864197  0.10581138]
 [-0.60502452 -0.97125484  0.08047038  0.1662411  -1.14908066]
 [-1.48446084 -1.12193232  0.69262912 -0.39790851 -0.31848659]
 [ 0.98603022 -0.63672289 -0.55914179  0.27752597 -0.97745619]
 [ 0.70183106  1.28724107 -0.68091339  0.56057638 -0.34886419]
 [ 1.39794761 -2.063898    0.04913099  0.65503111 -1.85